### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Fengjie446** [rainym00d/LLM4RS#7]
Hello, the student has been greatly inspired by reading your article, but cannot find the methods for pop and random in the code. Could you please take the time to provide them to the student? Thank you very much!

**Comment by rainym00d** [comment]
Thank you for your question! 

As the caption of Table 1 in the paper states, 'random' means that we will randomly select one item from five, while 'pop' means that we will sort the five items based on the interaction history of the entire dataset and choose the one with the most interaction history. 

Both of these methods are heuristic algorithms and do not require a specific model for implementation.

**Comment by Fengjie446** [comment]
Thank you for your reply, thank you very much!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "rainym00d/LLM4RS"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年1月5日(星期五) 中午1:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [rainym00d/LLM4RS] help (Issue #7)





 
Thank you for your question!
 
As the caption of Table 1 in the paper states, 'random' means that we will randomly select one item from five, while 'pop' means that we will sort the five items based on the interaction history of the entire dataset and choose the one with the most interaction history.
 
Both of these methods are heuristic algorithms and do not require a specific model for implementation.
